### ISSUE TITLE
TeleSign v1.0.0 Discussion

### ISSUE THREAD

**Issue by hmorales** [TeleSign/java_telesign#31]
There have been several suggestions on how to make the TeleSign Java SDK more useful. Some of the changes we are planning would introduce backwards compatibility issues. Below I have outlined a few of the changes we would like to introduce as part of v1.0.0. Please provide any feedback regarding the proposed changes (items in no particular order).

*  Adhere to Java naming conventions and cleanup inconsistencies.
  * ex: public Verify(String customer_id, String secret_key, int connectTimeout, int readTimeout) 
* Easier way to maintain request parameters as appose to just overloading methods. Especially useful when new features are introduced and code hasn't been updated. 
 * ex: Map<> parameter, Builder Pattern, others?
* Better error handling, currently errors are captured and written to System.err. We should introduce proper TSError classes and not write them to System.err.
* Better handling of response data. Its nice to have the actual field name described within a concrete class but it would also be useful to just return the raw data. This is especially true for products like PhoneID where new data nodes could be added to existing products. 
* Better unit testing. Today we have some unit test that aren't very useful and require that it runs against a live server.
* Ensure we support http/s proxies. This might already be supported.
* Update SDK to support missing products.
* Review current dependency list and see if they are really needed.
* Add support for Maven.
* Deprecate Ant builds?
* Add support for OSGi.
* Proper javadocs.
* Added User-Agent to http request so we can more easily track TS SDK based requests
* Update GitHub documentation and have tech writer review.

@freesoft and @gibffe and @Manmohan-TechM 

Thoughts?

**Comment by Manmohan-TechM** [comment]
Currently we have a method setTLSprotocol in Telesignrequest class which set the protocol version to TLSv1.2 .
Suggestion: Lets make the cipher list and protocol version configurable.
I have emailed you the code for doing above task for review.

**Comment by gibffe** [comment]
All good points.

I would split unit tests into unit & integration tests - currently they are mixed together which is confusing.

+1 for error handling 
+1 for moving to Maven

I think the SDK should use a http client with connection pooling as opposed to creating fresh connection upon every request - this may not be ideal at certain throughouts and/or proxy configurations. Apache HttpClient comes to mind - client code could inject its instance, configured as they see fit, use default otherwise.

**Comment by freesoft** [comment]
Current build configuration is way behind than latest build system support. Ant based one should be deprecated, and maven support for sure, and Gradle support will be nice-to-have, but doesn't necessary for v1.0.0.

**Comment by hmorales** [comment]
Thank you all for your feedback. I will be creating a new milestone and related tasks to track these items.
