### ISSUE TITLE
OkHttp 3.0

### ISSUE THREAD

**Issue by ostronom** [TeleSign/java_telesign#58]
Looks like, there is no okhttp 3.3.0 available in any of well-known repositories. Have you considered an upgrade?

**Comment by jarradsl** [comment]
Hi @ostronom,

Thanks for the feedback. Unless I am misundertanding your query, we specify okhttp with a min version of 3.3 [as follows](https://github.com/TeleSign/java_telesign/blob/master/build.gradle#L20):

dependencies {
    compile 'com.squareup.okhttp3:okhttp:[3.3,)'
    ...
}

That means you should be free to build and run the project with okhttp including version 3.3.0 and up to 3.9.0 (current latest). The Central Repository has past and current versions available as listed [here](https://mvnrepository.com/artifact/com.squareup.okhttp3/okhttp). Perhaps you were looking under  com.squareup.okhttp and not com.squareup.okhttp**3**?

Cheers,
Jarrad
