### ISSUE TITLE
Complilation issue

### ISSUE THREAD

**Issue by ZebpayDipen** [TeleSign/java_telesign#63]
compile 'com.telesign.rest:telesign:(insert latest version)'

What is the latest version?
And how can I write the above line?
Like:
compile 'com.telesign.rest:telesign:(2.2.2)' OR
compile 'com.telesign.rest:telesign:2.2.2'

**Comment by erikkai** [comment]
You would write it the second way:

compile 'com.telesign.rest:telesign:2.2.2'

**Comment by ZebpayDipen** [comment]
I wrote it in that way but still I m getting error while gradle compilation

Is there anything else i need to write somewhere else???

**Comment by erikkai** [comment]
Did you make sure it is inside the dependency block?

Also did you specify a jar repository for the gradle to lookup the dependencies with (mavenCentral or jcenter). For example:

repositories {
    mavenCentral()
}

dependencies {
    compile ‘com.telesign:telesign:2.2.2’
}
